### ISSUE TITLE
Readme does not show quick overview of what the project does

### ISSUE THREAD

**Issue by SamuelHowes-ma** [BU-NU-CLOUD-SP16/Automated-Release-Notes#32] opened 2016-04-25 17:21 UTC
A new user wants to quickly see what the plugin does. Add screenshots to the Readme as the first section with the title "Overview". This section should look something like the following:

This plugin takes a commit message:
[screenshot of a git commit message]

And parses a Visual Studio Team Services Work item number out of it to generate release notes:
[screenshot of final output]

**Comment by samhowes** [comment] 2016-04-25 17:36
Duplicate of #24.

**Closed as completed by samhowes** 2016-04-25 17:36 UTC
